# Generated by Django 6.0.4 on 2026-04-30 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('ubication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupBP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_list', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('list_only_for_members', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SellerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaxDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=18)),
                ('business_activity', models.CharField(max_length=100)),
                ('payment_condition', models.IntegerField()),
                ('term_claims', models.CharField(max_length=255)),
                ('client_export', models.CharField(max_length=255)),
                ('bp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.bptype')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.customertype')),
                ('group_bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.groupbp')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.branch')),
                ('seller_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.sellertype')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.IntegerField()),
                ('doc_num', models.IntegerField()),
                ('folio', models.IntegerField()),
                ('date_document', models.DateField()),
                ('delivery_date', models.DateField()),
                ('delivery_schedule', models.DateTimeField()),
                ('reference', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('total_before_discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_document', models.DecimalField(decimal_places=2, max_digits=12)),
                ('code_sale', models.IntegerField()),
                ('office_address', models.CharField(max_length=255)),
                ('address_delivery', models.CharField(max_length=255)),
                ('related_docEntry', models.IntegerField(blank=True, null=True)),
                ('document_status', models.CharField(max_length=50)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.businesspartner')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.deliverytype')),
                ('payment_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.paymentterms')),
                ('sale_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.saletype')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.seller')),
                ('tax_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.taxdocumenttype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
    ]
