# Generated by Django 6.0.4 on 2026-04-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountConfig',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('sale_type', models.CharField(max_length=50)),
                ('max_discount_limit', models.IntegerField()),
                ('brand_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Discount Config',
                'verbose_name_plural': 'Discount Configs',
                'db_table': 'discount_config',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(default='https://ledstudiocl.vtexassets.com/assets/vtex.file-manager-graphql/images/14ecba9f-2814-4029-9e0e-e5e6b9e2869c___b2a5497dbc81c0adc5576c48b2eeb27b.jpg', max_length=255)),
                ('total_stock', models.IntegerField(default=0)),
                ('list_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('max_store_discount', models.FloatField()),
                ('max_project_discount', models.FloatField()),
                ('product_url', models.CharField(max_length=255)),
                ('brand', models.CharField(default='No Brand', max_length=20, null=True)),
                ('cost', models.FloatField(default=0)),
                ('is_discontinued', models.CharField(default='0', max_length=10, null=True)),
                ('is_inactive', models.CharField(default='NO', max_length=10, null=True)),
                ('tree_type', models.CharField(default='DEFAULT', max_length=50, null=True)),
                ('certification', models.CharField(default='4', max_length=100, null=True)),
                ('image_status_http', models.IntegerField(blank=True, default=9999, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
