# Generated by Django 6.0.4 on 2026-06-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_drop_business_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='active_paths',
            field=models.CharField(blank=True, help_text='Segmentos de URL (kebab-case) separados por coma para resaltar el ítem como activo, ej: "list-of-quotes,generate-quote". Si está vacío se deriva automáticamente de url_name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url_name',
            field=models.CharField(blank=True, help_text='Nombre de la URL Django. Déjalo vacío si el ítem solo abre un dropdown.', max_length=80),
        ),
    ]
