# Generated by Django 6.0.4 on 2026-06-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_alter_navitem_active_paths_alter_navitem_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='mobile',
        ),
    ]
